development:
  sessions:
    default:
      database: pophealth-development
      hosts:
        - 192.168.1.48:27017
test:
  sessions:
    default:
      database: pophealth-test
      hosts:
        - 192.168.1.48:27017
production:
  sessions:
    default:
      database: pophealth-production
      hosts:
        - 192.168.1.48:27017
